[package]
name = "reinforcex"
version = "0.0.2"
edition = "2021"
description = "Deep Reinforcement Learning Framework"
license = "MIT"
repository = "https://github.com/kakky-hacker/reinforcex"
readme = "README.md"
keywords = ["rust", "drl"]
categories = ["algorithms"]
exclude = ["src/examples", "src/main.rs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8"
tch = {version="0.18.0"}
torch-sys = {version="0.18.0", features=["download-libtorch"]}
ndarray = "0.15"
gym = { git = "https://github.com/kakky-hacker/gym-rs.git", branch = "master", version="2.2.1" }