# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: env_server.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x65nv_server.proto\x12\tenvserver\"\x1b\n\x0cResetRequest\x12\x0b\n\x03\x65nv\x18\x01 \x01(\t\"8\n\rResetResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x13\n\x0bobservation\x18\x02 \x03(\x02\"1\n\x0bStepRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x02 \x01(\x05\"\x9f\x01\n\x0cStepResponse\x12\x13\n\x0bobservation\x18\x01 \x03(\x02\x12\x0e\n\x06reward\x18\x02 \x01(\x02\x12\x0c\n\x04\x64one\x18\x03 \x01(\x08\x12/\n\x04info\x18\x04 \x03(\x0b\x32!.envserver.StepResponse.InfoEntry\x1a+\n\tInfoEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\x81\x01\n\nEnvService\x12:\n\x05Reset\x12\x17.envserver.ResetRequest\x1a\x18.envserver.ResetResponse\x12\x37\n\x04Step\x12\x16.envserver.StepRequest\x1a\x17.envserver.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'env_server_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_STEPRESPONSE_INFOENTRY']._options = None
  _globals['_STEPRESPONSE_INFOENTRY']._serialized_options = b'8\001'
  _globals['_RESETREQUEST']._serialized_start=31
  _globals['_RESETREQUEST']._serialized_end=58
  _globals['_RESETRESPONSE']._serialized_start=60
  _globals['_RESETRESPONSE']._serialized_end=116
  _globals['_STEPREQUEST']._serialized_start=118
  _globals['_STEPREQUEST']._serialized_end=167
  _globals['_STEPRESPONSE']._serialized_start=170
  _globals['_STEPRESPONSE']._serialized_end=329
  _globals['_STEPRESPONSE_INFOENTRY']._serialized_start=286
  _globals['_STEPRESPONSE_INFOENTRY']._serialized_end=329
  _globals['_ENVSERVICE']._serialized_start=332
  _globals['_ENVSERVICE']._serialized_end=461
# @@protoc_insertion_point(module_scope)
